# Generated by Django 5.0.1 on 2024-07-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSave',
            fields=[
                ('test_save_pk', models.AutoField(db_column='Test_Save_PK', primary_key=True, serialize=False)),
                ('test_name', models.CharField(blank=True, db_column='Test_Name', max_length=45, null=True)),
                ('test_num', models.IntegerField(blank=True, db_column='Test_Num', null=True)),
                ('test_uid', models.CharField(blank=True, db_column='Test_UID', max_length=45, null=True)),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('input', models.CharField(blank=True, max_length=255, null=True)),
                ('result', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'test_save',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval', models.CharField(blank=True, max_length=100, null=True)),
                ('test_cases', models.ManyToManyField(related_name='schedules', to='testsel.testsave')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsel.testsave')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsel.testschedule')),
            ],
        ),
    ]
