# Generated by Django 5.0.1 on 2024-09-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tclist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ts',
            options={},
        ),
    ]
