# Generated by Django 5.0.1 on 2024-09-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tc',
            fields=[
                ('tc_num', models.AutoField(db_column='TC_Num', primary_key=True, serialize=False)),
                ('tc_type', models.CharField(blank=True, db_column='TC_Type', max_length=255, null=True)),
                ('tc_url', models.CharField(blank=True, db_column='TC_Url', max_length=255, null=True)),
                ('tc_target', models.CharField(blank=True, db_column='TC_Target', max_length=255, null=True)),
                ('tc_input', models.TextField(blank=True, db_column='TC_Input', null=True)),
                ('tc_result', models.TextField(blank=True, db_column='TC_Result', null=True)),
            ],
            options={
                'db_table': 'tc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TcList',
            fields=[
                ('tc_pid', models.AutoField(db_column='TC_PID', primary_key=True, serialize=False)),
                ('tc_name', models.CharField(db_column='TC_Name', max_length=255)),
                ('tc_describe', models.TextField(blank=True, db_column='TC_Describe', null=True)),
            ],
            options={
                'db_table': 'tc_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ts',
            fields=[
                ('ts_num', models.AutoField(db_column='TS_Num', primary_key=True, serialize=False)),
                ('ts_start', models.DateTimeField(blank=True, db_column='TS_Start', null=True)),
                ('ts_end', models.DateTimeField(blank=True, db_column='TS_End', null=True)),
                ('ts_repeat_interver', models.CharField(blank=True, db_column='TS_Repeat_Interver', max_length=255, null=True)),
                ('ts_repeat_interval_value', models.CharField(blank=True, db_column='TS_Repeat_Interval_value', max_length=255, null=True)),
            ],
            options={
                'db_table': 'ts',
                'managed': False,
            },
        ),
    ]
